/* Kotoba Dungeon V0.1 — view/controller. No edits to Kotoba reviews. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id);
 const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const engine=window.KotobaDungeonEngine,source=window.KotobaDungeonSource;
 let data=null,selected='known',tick=null;
 const icons={blade:'⚔️',ward:'🛡️',tea:'🍵',ribbon:'🪢',focus:'🔮',hourglass:'⌛'};
 const texts={blade:['Ink Blade','+4 Attack'],ward:['Paper Ward','+18 HP + Heilen'],tea:['Warm Tea','+28 HP'],ribbon:['Spirit Ribbon','+10 Shield'],focus:['Focus Charm','Jede 3. richtige Antwort: +10 Schaden'],hourglass:['Hourglass','Boss-Challenge: +10 Sekunden']};
 const foeEmoji={'Paper Wisp':'👻','Ink Imp':'👾','Mist Fox':'🦊','The Archivist':'🧙'};
 function alert(message){const a=$('alert');a.hidden=!message;a.textContent=message||'';}
 function selection(){if(selected==='starter')return data.starter;if(selected==='guru')return data.learned.filter(v=>v.stage>=5||v.guruPassed);return data.learned;}
 function deck(){const cards=selection();engine.setDeck(cards);return cards;}
 function handleData(d){data=d;const previous=engine.snapshot().run;if(previous&&previous.phase!=='ended'){selected=previous.source==='starter'?'starter':'known';if(selected==='known'&&data.learned.length<3)alert('Für deinen gespeicherten Run fehlt gerade dein synchronisierter Vokabelpool. Öffne Kotoba Quest und lade neu oder nutze den Export-Import.');}if(!previous&&data.learned.length<3&&data.starter.length>=3)selected='starter';deck();render();}
 async function init(){try{handleData(await source.load());}catch(e){alert('Wörter konnten nicht geladen werden: '+String(e.message||e));data={learned:[],starter:[],vocabulary:[],packError:String(e),hasLiveSave:false};render();}}
 function info(){return `<div class="info-strip"><span class="chip">⚔ ${engine.snapshot().meta.runs} Runs</span><span class="chip">✦ ${engine.snapshot().meta.wins} Siege</span><span class="chip">💎 ${engine.snapshot().meta.shards} Scherben</span></div>`;}
 function hero(){const m=engine.snapshot().meta,n=data.learned.length,g=data.learned.filter(v=>v.stage>=5||v.guruPassed).length,starter=data.starter.length;const ready=selection().length>=3;
 return `<div class="front-grid"><section class="card hero"><p class="eyebrow">A SMALL ROGUELITE EXPERIMENT</p><h1>Just one more battle.</h1><p class="hero-desc">Drei entspannte Vokabel-Kämpfe. Ausrüstung wählen. Dann der Boss — normal oder als freiwillige 60-Sekunden-Challenge.</p><div class="stats"><div class="stat"><strong>${m.runs}</strong><span>Runs</span></div><div class="stat"><strong>${m.wins}</strong><span>Boss-Siege</span></div><div class="stat"><strong>${m.shards} ✦</strong><span>Dungeon-Scherben</span></div></div><button type="button" class="main-btn" data-action="start" ${ready?'':'disabled'}>Run starten →</button><p class="subtle" style="color:#f3e0ec;margin:13px 0 0">Keine echten SRS-Reviews, keine Life-RPG-Coins. Kostenlos wiederholbar.</p></section><div class="right-stack"><section class="card"><p class="eyebrow">YOUR WORD DECK</p><h2>Welche Wörter?</h2><label class="deck-option"><input type="radio" name="deck" value="known" ${selected==='known'?'checked':''} ${n<3?'disabled':''}><span><strong>Meine gelernten Wörter</strong><small>${n} Core/Mining · alle bereits eingeführten SRS-Stufen</small></span></label><label class="deck-option"><input type="radio" name="deck" value="guru" ${selected==='guru'?'checked':''} ${g<3?'disabled':''}><span><strong>Guru & höher</strong><small>${g} Wörter für vertrauten Wortschatz</small></span></label><label class="deck-option"><input type="radio" name="deck" value="starter" ${selected==='starter'?'checked':''} ${starter<3?'disabled':''}><span><strong>Starter-Proberunde</strong><small>${starter} echte Core-Begriffe, auch ohne importierten Spielstand</small></span></label><p class="subtle">${data.hasLiveSave?`Kotoba-Speicher erkannt · ${data.vocabulary.length} lesbare Einträge.`:'Noch kein vollständiger lokaler Kotoba-Spielstand erkannt.'} ${data.packError?'Der öffentliche Core-Katalog konnte nicht geladen werden.':''}</p><label class="import-box">📄 Kotoba-Exportdatei nur für diese Sitzung einlesen<input type="file" id="dungeonImport" accept=".json,application/json" aria-label="Kotoba Exportdatei auswählen"></label></section><section class="card"><p class="eyebrow">PERMANENT GEAR</p><h3>Dauerhafte Verbesserungen</h3><div class="perks">${[['heart','♥ Mehr Ausdauer','+12 Start-HP'],['strike','⚔ Stärkerer Angriff','+2 Basisschaden']].map(([key,name,desc])=>{const lvl=m.perks[key]||0,cost=10+lvl*10;return `<div class="perk"><div><strong>${name}</strong><br><span class="subtle">${desc} · ${lvl}/4</span></div><button type="button" class="small-button" data-perk="${key}" ${m.shards<cost||lvl>=4?'disabled':''}>${lvl>=4?'Max':cost+' ✦'}</button></div>`}).join('')}</div></section></div></div>`;}
 function fighter(r){const hp=Math.max(0,100*r.hp/r.maxHp),enemy=Math.max(0,100*r.enemy.hp/r.enemy.maxHp);return `<div class="battle"><div class="arena"><div class="fighter"><div class="sprite avatar" aria-label="Abenteuer-Avatar"><span class="body"></span><span class="face"></span><span class="hair"></span><span class="eyes">• •</span></div><strong>Du · HP ${r.hp}/${r.maxHp}</strong><div class="meter"><i style="width:${hp}%"></i></div><small>${r.shield?'🛡 '+r.shield+' Shield · ':''}⚔ ${r.atk} Angriff</small></div><div class="versus">VS</div><div class="fighter"><div class="sprite foe"><span class="creature" aria-hidden="true">${foeEmoji[r.enemy.name]||'👹'}</span></div><strong>${E(r.enemy.name)} · ${r.enemy.hp}/${r.enemy.maxHp}</strong><div class="meter enemy-meter"><i style="width:${enemy}%"></i></div><small>${r.mode==='boss'?'Boss':'Normaler Gegner'}</small></div></div><div class="battle-meta"><span>💰 ${r.gold} Dungeon-Gold · ⚡ ${r.correct}/${r.attempts} richtige Treffer</span>${r.timed?`<span class="timer" id="bossTimer" role="timer">--:--</span>`:`<span class="chip">Kein Zeitdruck</span>`}</div></div>`;}
 function track(r){return `<div class="run-nav"><div class="floor-track">${[1,2,3,4].map(n=>`<span class="${n===r.floor?'on':''}">${n===4?'✦ Boss':'${n}'}</span>`).join('')}</div><button type="button" class="ghost" data-action="abandon">Run beenden</button></div>`;}
 function question(r){const q=r.question;if(!q)return '<p>Keine gültige Frage verfügbar.</p>';const answers=q.options?`<div class="answers">${q.options.map((x,i)=>`<button type="button" data-answer="${E(x)}" class="answer"><span class="subtle">${i+1}</span><br>${E(x)}</button>`).join('')}</div>`:`<form id="textForm" class="text-entry"><input id="answerInput" autocomplete="off" autocapitalize="off" spellcheck="false" lang="ja" placeholder="Lesung eingeben …" aria-label="Deine Antwort" required><button class="main-btn" type="submit">Angreifen →</button></form>`;return `<section class="card question-card"><div class="question-header"><p class="eyebrow">${E(q.type==='reading'?'READING ATTACK':q.type==='cloze'?'SENTENCE SPELL':'VOCAB ATTACK')}</p><span class="chip">${r.floor===4?'Boss':'Floor '+r.floor}</span></div><div><p class="muted" style="text-align:center;margin:0">${E(q.label)}</p><div class="question-prompt" lang="${q.type==='deJapanese'?'de':'ja'}">${E(q.prompt)}</div></div>${answers}<p class="subtle">Falsch ist kein Drama: Du siehst danach die richtige Antwort. In normalen Kämpfen gibt es keinen Timer.</p></section>`;}
 function feedback(r){const f=r.feedback;if(!f)return '';return `<section class="card"><div class="feedback ${f.correct?'':'wrong'}"><h3>${f.correct?'Treffer! ✦':'Noch nicht ganz.'}</h3><p>${f.correct?`${f.damage} Schaden · ${r.gold} Gold im Run`:`${f.hurt} HP verloren. Hier ist die richtige Verbindung:`}</p><strong>${E(f.hint)}</strong></div>${r.phase==='battle'?'<div class="button-row" style="margin-top:12px"><button class="main-btn" data-action="advance">Nächster Angriff →</button></div>':''}</section>`;}
 function loot(r){return `<section class="card"><p class="eyebrow">A SMALL REWARD</p><h2>Der kleine Händler</h2><p class="muted">💰 ${r.gold} Gold · Wähle eine Ausrüstung oder spare für Extra-Scherben am Run-Ende. Diese Ausrüstung gilt für den aktuellen Run. ${r.floor===3?'Danach wartet der Boss.':'Danach beginnt der nächste Kampf.'}</p><div class="loot-grid">${r.loot.map(k=>`<button class="loot-option" data-loot="${k}" ${r.gold<engine.prices[k]?'disabled':''}><span class="loot-icon">${icons[k]}</span><strong>${texts[k][0]}</strong><small>${texts[k][1]} · ${engine.prices[k]} Gold</small></button>`).join('')}</div><button class="ghost" type="button" data-loot="skip" style="margin-top:14px">Gold behalten und weiter →</button></section>`;}
 function bossChoice(r){return `<section class="card"><p class="eyebrow">FLOOR FOUR · THE BOSS</p><h2>Bereit für die Boss Challenge?</h2><p class="muted">Deine drei Siege und deine Ausrüstung helfen dir. Du entscheidest jetzt, ob du mit oder ohne Zeitdruck kämpfst.</p><div class="boss-options"><button class="boss-choice" data-boss="normal"><span class="loot-icon">🛡️</span><strong>Normaler Bosskampf</strong><small>Kein Timer. Lerne in Ruhe, wie bei den normalen Gegnern.</small></button><button class="boss-choice" data-boss="timed"><span class="loot-icon">⚡</span><strong>60-Sekunden-Challenge</strong><small>Jede richtige Antwort verursacht Schaden. Bei Ablauf endet der Run. Bonus-Scherben bei Sieg.</small></button></div></section>`;}
 function ended(r){const m=engine.snapshot().meta;return `<section class="card ended"><div class="trophy">${r.result.won?'🏆':'🌱'}</div><p class="eyebrow">RUN COMPLETE</p><h1>${r.result.won?'Dungeon geschafft!':'Nächster Run, neues Glück.'}</h1><p>${E(r.result.reason)}</p><div class="info-strip" style="justify-content:center;margin:17px 0"><span class="chip">${r.correct}/${r.attempts} richtig</span><span class="chip">${r.kills} Gegner</span><span class="chip">+${r.result.shards} Scherben</span></div><p class="muted">Dein Japanisch-SRS bleibt unverändert. Du behältst ${m.shards} Dungeon-Scherben für permanente Ausrüstung.</p><div class="button-row" style="justify-content:center"><button class="main-btn" data-action="restart">Noch einen Run →</button><button class="alt-btn" data-action="home">Zum Camp</button></div></section>`;}
 function render(){if(!data)return;const s=engine.snapshot(),r=s.run;if(!r){$('game').innerHTML=hero();return;}if(r.phase==='ended'){$('game').innerHTML=ended(r);return;}let body='';if(r.phase==='battle'){body=fighter(r)+(r.feedback?feedback(r):question(r));}else if(r.phase==='loot'){body=fighter(r)+feedback(r)+loot(r);}else if(r.phase==='bossSelect'){body=fighter(r)+bossChoice(r);}else{body='<p>Der Run ist bereit.</p>';}const gear=r.gear.length?`<div class="info-strip">${r.gear.map(k=>`<span class="chip">${icons[k]} ${E(texts[k][0])}</span>`).join('')}</div>`:'';$('game').innerHTML=`<div class="run-wrap">${track(r)}${gear}${body}</div>`;updateTimer();}
 function updateTimer(){const r=engine.snapshot().run;const el=$('bossTimer');if(!r||!r.timed||r.phase!=='battle'||!el)return;const seconds=Math.max(0,Math.ceil((r.bossDeadline-Date.now())/1000));el.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds<=0){engine.timeout();render();}}
 function restoreDeck(){const r=engine.snapshot().run;if(r?.source==='starter')engine.setDeck(data.starter);else engine.setDeck(data.learned);}
 function act(action){try{if(action==='start'){deck();engine.start({starter:selected==='starter'});}if(action==='advance')engine.advance();if(action==='abandon'&&confirm('Diesen Run beenden? Du behältst deine bisherigen Dungeon-Scherben.'))engine.abandon();if(action==='restart'||action==='home'){engine.resetRun?.();if(action==='restart'){deck();engine.start({starter:selected==='starter'});} }render();}catch(err){alert(err.message||String(err));}}
 document.addEventListener('click',e=>{if(e.target.closest('#infoBtn')){$('helpDialog').showModal();return;}if(e.target.closest('[data-close-help]')){$('helpDialog').close();return;}const p=e.target.closest('[data-perk]');if(p){engine.perk(p.dataset.perk);render();return;}const loot=e.target.closest('[data-loot]');if(loot){engine.chooseLoot(loot.dataset.loot);render();return;}const boss=e.target.closest('[data-boss]');if(boss){engine.boss(boss.dataset.boss==='timed');render();return;}const choice=e.target.closest('[data-answer]');if(choice){engine.answer(choice.dataset.answer);render();return;}const action=e.target.closest('[data-action]');if(action){act(action.dataset.action);return;}});
 document.addEventListener('submit',e=>{if(e.target.id!=='textForm')return;e.preventDefault();const answer=$('answerInput')?.value||'';engine.answer(answer);render();});
 document.addEventListener('change',async e=>{if(e.target.name==='deck'){selected=e.target.value;deck();render();return;}if(e.target.id==='dungeonImport'&&e.target.files?.[0]){try{const file=e.target.files[0];if(file.size>18*1024*1024)throw Error('Die Datei ist zu groß.');const parsed=JSON.parse(await file.text());let payload=parsed;if(!Array.isArray(payload.vocabulary)&&parsed.data&&Array.isArray(parsed.data.vocabulary))payload=parsed.data;if(!Array.isArray(payload.vocabulary))throw Error('Die Datei enthält kein Kotoba-Vokabelverzeichnis.');if(!Array.isArray(data?.catalog)||!data.catalog.length)throw Error('Core-Pack fehlt.');const base=data.catalog||[];const x=source.hydrate({data:payload},base);const known=x.filter(v=>v.stage>0||v.guruPassed);if(known.length<3)throw Error('Im Export wurden weniger als drei gelernte vollständige Wörter gefunden.');data={...data,vocabulary:x,learned:known,hasLiveSave:true};selected='known';alert(`Für diese Sitzung geladen: ${known.length} gelernte Wörter. Kotoba-SRS wurde nicht verändert.`);engine.setDeck(known);render();}catch(err){alert('Import fehlgeschlagen: '+String(err.message||err));}e.target.value='';}});
 // No setInterval progress calculations: only wall-clock remaining time depends on the tick.
 tick=setInterval(updateTimer,250);
 window.addEventListener('focus',()=>{if(!engine.snapshot().run){init();return;}restoreDeck();updateTimer();});
 init();
})();
