/* Kotoba Dungeon V0.4 — persistent camp economy and typed-first combat.
   Dungeon state only. Never writes Kotoba SRS or Life RPG ledgers. */
(() => {
  'use strict';
  const STORE='kotobaQuestDungeonV1'; // preserve V0.1/V0.2 local progress
  const clone=value=>JSON.parse(JSON.stringify(value));
  const clamp=(n,lo,hi)=>Math.max(lo,Math.min(hi,n));
  const norm=v=>String(v??'').normalize('NFKC').trim().toLocaleLowerCase('de-DE').replace(/[.!?。！？\s]+$/g,'').replace(/\s+/g,' ');
  const kana=v=>String(v??'').normalize('NFKC').replace(/[\u30a1-\u30f6]/g,c=>String.fromCharCode(c.charCodeAt(0)-96));
  const romaji={kya:'きゃ',kyu:'きゅ',kyo:'きょ',gya:'ぎゃ',gyu:'ぎゅ',gyo:'ぎょ',sha:'しゃ',shu:'しゅ',sho:'しょ',shi:'し',chi:'ち',tsu:'つ',cha:'ちゃ',chu:'ちゅ',cho:'ちょ',ja:'じゃ',ju:'じゅ',jo:'じょ',nya:'にゃ',nyu:'にゅ',nyo:'にょ',hya:'ひゃ',hyu:'ひゅ',hyo:'ひょ',mya:'みゃ',myu:'みゅ',myo:'みょ',rya:'りゃ',ryu:'りゅ',ryo:'りょ',kka:'っか',ka:'か',ki:'き',ku:'く',ke:'け',ko:'こ',ga:'が',gi:'ぎ',gu:'ぐ',ge:'げ',go:'ご',sa:'さ',si:'し',su:'す',se:'せ',so:'そ',za:'ざ',ji:'じ',zi:'じ',zu:'ず',ze:'ぜ',zo:'ぞ',ta:'た',ti:'ち',te:'て',to:'と',da:'だ',de:'で',do:'ど',na:'な',ni:'に',nu:'ぬ',ne:'ね',no:'の',ha:'は',hi:'ひ',hu:'ふ',fu:'ふ',he:'へ',ho:'ほ',ba:'ば',bi:'び',bu:'ぶ',be:'べ',bo:'ぼ',pa:'ぱ',pi:'ぴ',pu:'ぷ',pe:'ぺ',po:'ぽ',ma:'ま',mi:'み',mu:'む',me:'め',mo:'も',ya:'や',yu:'ゆ',yo:'よ',ra:'ら',ri:'り',ru:'る',re:'れ',ro:'ろ',wa:'わ',wo:'を',a:'あ',i:'い',u:'う',e:'え',o:'お',n:'ん'};
  function toHiragana(v){let s=norm(v).replace(/[-_ ]/g,'').replace(/[āá]/g,'a').replace(/[īí]/g,'i').replace(/[ūú]/g,'u').replace(/[ēé]/g,'e').replace(/[ōó]/g,'ou');if(/[ぁ-ゖァ-ヶ]/u.test(s))return kana(s);if(!/^[a-z']+$/i.test(s))return kana(s);let out='';while(s){if(s[0]==="'"){s=s.slice(1);continue;}if(s.length>=2&&s[0]===s[1]&&/[bcdfghjklmpqrstvwxyz]/.test(s[0])&&s[0]!=='n'){out+='っ';s=s.slice(1);continue;}if(s[0]==='n'&&(s.length===1||s[1]==="'"||!/[aiueoy]/.test(s[1]))){out+='ん';s=s.slice(s[1]==="'"?2:1);continue;}let found=false;for(const n of [3,2,1]){const key=s.slice(0,n);if(romaji[key]){out+=romaji[key];s=s.slice(n);found=true;break;}}if(!found)return kana(v);}return out;}
  const STARTER={version:1,meta:{shards:0,wins:0,runs:0,bestFloor:0,perks:{heart:0,strike:0},history:[],gold:0,xp:0,level:1,trainingPoints:0,training:{heart:0,strike:0},equipment:{blade:0,ward:0,focus:0,hourglass:0},settings:{answerMode:'typed',autoKana:true}},run:null,weak:{}};
  function read(){try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved?.version===1&&saved.meta&&typeof saved.meta==='object')return saved;}catch(_){}return clone(STARTER);}
  let state=read(),deck=[];
  function migrate(){const m=state.meta;m.shards=Math.max(0,Number(m.shards)||0);m.gold=Math.max(0,Number(m.gold)||0);m.xp=Math.max(0,Number(m.xp)||0);m.level=Math.max(1,Math.floor(Number(m.level)||1));m.trainingPoints=Math.max(0,Math.floor(Number(m.trainingPoints)||0));m.perks={heart:0,strike:0,...m.perks};m.training={heart:0,strike:0,...m.training};m.equipment={blade:0,ward:0,focus:0,hourglass:0,...m.equipment};m.settings={answerMode:'typed',autoKana:true,...m.settings};m.settings.autoKana=m.settings.autoKana!==false;if(!['typed','choice'].includes(m.settings.answerMode))m.settings.answerMode='typed';if(!Array.isArray(m.history))m.history=[];if(!state.weak||typeof state.weak!=='object')state.weak={};const r=state.run;if(r){if(r.phase==='loot'){r.phase='victory';r.loot=null;}r.floorCorrect=Math.max(0,Number(r.floorCorrect)||0);r.floorAttempts=Math.max(0,Number(r.floorAttempts)||0);r.gold=Number(r.gold)||0;r.xpEarned=Number(r.xpEarned)||0;r.goldEarned=Number(r.goldEarned)||0;}}migrate();
  function persist(){try{localStorage.setItem(STORE,JSON.stringify(state));}catch(err){state.lastSaveError=String(err);}}
  const EQUIPMENT={blade:{name:'Ink Blade',desc:'+3 Angriff pro Rang',base:22,step:18,max:5},ward:{name:'Paper Ward',desc:'+6 Start-Schild pro Rang',base:20,step:16,max:5},focus:{name:'Focus Charm',desc:'Bonus beim dritten Treffer',base:30,step:22,max:4},hourglass:{name:'Hourglass',desc:'+5 s bei Zeit-Boss pro Rang',base:25,step:20,max:3}};
  function shopPrice(key){const item=EQUIPMENT[key];if(!item)return Infinity;return item.base+(state.meta.equipment[key]||0)*item.step;}
  function buy(key){const m=state.meta,item=EQUIPMENT[key];if(state.run&&state.run.phase!=='ended'||!item)return false;const level=m.equipment[key]||0,price=shopPrice(key);if(level>=item.max||m.gold<price)return false;m.gold-=price;m.equipment[key]=level+1;persist();return true;}
  function train(key){const m=state.meta;if(state.run&&state.run.phase!=='ended'||!['heart','strike'].includes(key)||m.trainingPoints<1)return false;m.trainingPoints--;m.training[key]=(m.training[key]||0)+1;persist();return true;}
  function exchangeShards(){const m=state.meta;if(state.run&&state.run.phase!=='ended'||m.shards<1)return false;m.gold+=m.shards*6;m.shards=0;persist();return true;}
  const levelNeed=level=>18+Math.max(1,level)*12;
  function addXP(value){const m=state.meta;m.xp+=value;let levels=0;while(m.xp>=levelNeed(m.level)){m.xp-=levelNeed(m.level);m.level++;m.trainingPoints++;levels++;}return levels;}
  function setDeck(cards){deck=(cards||[]).filter(v=>v?.id&&v.word&&v.reading&&Array.isArray(v.meanings)&&v.meanings.length);if(state.run?.phase==='battle'&&state.run.question&&deck.length){const q=state.run.question;if(q.mode!==state.meta.settings.answerMode){const v=deck.find(x=>x.id===q.id);if(v)state.run.question=makeQuestion(v,q.type);persist();}}return deck.length;}
  const stageTypes=['jpMeaning','deJapanese','reading','kanaWord','cloze'];
  function pick(items){return items[Math.floor(Math.random()*items.length)];}
  function shuffle(items){const out=items.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
  function poolPick(){const recent=state.run?.recent||[];const weighted=deck.map(v=>({v,w:1+(state.weak[v.id]||0)*.8+((v.stage||0)<5?.8:0)}));let items=weighted.filter(x=>!recent.includes(x.v.id));if(!items.length)items=weighted;const total=items.reduce((s,x)=>s+x.w,0);let roll=Math.random()*total;return(items.find(x=>(roll-=x.w)<=0)||items.at(-1)).v;}
  function meaningSet(v){return [...v.meanings,...v.acceptedMeanings||[],...v.synonyms||[],...v.meaningAlternatives||[]].filter(Boolean);}
  function alternativesByMeaning(v){const labels=new Set(meaningSet(v).map(norm));return deck.filter(x=>meaningSet(x).some(y=>labels.has(norm(y))));}
  function makeQuestion(v=null,type=null){if(!deck.length)return null;v=v||poolPick();const mode=state.meta.settings.answerMode,typed=mode==='typed';const valid=stageTypes.filter(t=>t!=='reading'||v.word!==v.reading).filter(t=>t!=='kanaWord'||!typed&&v.reading!==v.word).filter(t=>t!=='cloze'||(v.example&&v.example.includes(v.word)&&v.example!==v.word&&!v.example.includes('という言葉')&&!v.example.includes('「')&&v.exampleTranslation));type=valid.includes(type)?type:pick(valid.length?valid:['jpMeaning']);const word=v.word,reading=v.reading,meaning=v.meanings[0];let prompt='',label='',correct='',alt=[],options=null,detail='';const bank=deck.filter(x=>x.id!==v.id);
    const optionsOf=(correct,distractors)=>{const distinct=[...new Set(distractors.filter(x=>x!==correct&&x))];return shuffle([correct,...shuffle(distinct).slice(0,3)]);};
    if(type==='jpMeaning'){prompt=word;label='Was bedeutet das Wort?';correct=meaning;alt=meaningSet(v);if(!typed)options=optionsOf(meaning,bank.flatMap(x=>x.meanings.slice(0,1)).filter(x=>!alt.some(a=>norm(a)===norm(x))));}
    if(type==='deJapanese'){prompt=meaning;label=typed?'Japanisches Wort oder Lesung eingeben.':'Welches japanische Wort passt?';correct=word;const same=alternativesByMeaning(v);alt=[...same.flatMap(x=>[x.word,x.reading,...x.acceptedReadings||[]])];if(!typed)options=optionsOf(word,bank.filter(x=>!same.includes(x)).map(x=>x.word));detail=typed?'Kana, Kanji oder Rōmaji sind möglich.':'';}
    if(type==='reading'){prompt=word;label='Wie liest man das Wort? (Kana oder Rōmaji)';correct=reading;alt=[reading,...v.acceptedReadings||[]];if(!typed)options=optionsOf(reading,bank.map(x=>x.reading).filter(x=>!alt.includes(x)));}
    if(type==='kanaWord'){prompt=reading;label='Welche Schreibweise gehört zu dieser Lesung?';correct=word;alt=deck.filter(x=>kana(x.reading)===kana(reading)).map(x=>x.word);options=optionsOf(word,bank.filter(x=>!alt.includes(x.word)).map(x=>x.word));}
    if(type==='cloze'){prompt=v.example.replace(word,'＿＿＿');label=typed?'Setze das japanische Wort ein (Wort oder Lesung).':'Welches Wort ergänzt den Satz?';correct=word;alt=[word,reading,...v.acceptedReadings||[]];detail=`Gesuchtes Stichwort: ${meaning}`;if(!typed)options=optionsOf(word,bank.map(x=>x.word));}
    const hint=`${word} · ${reading} · ${meaningSet(v).join(' / ')}${v.example?` · ${v.example}`:''}`;
    return{id:v.id,type,mode,prompt,label,correct,options,alt,hint,detail,example:v.example,translation:v.exampleTranslation};
  }
  function setMode(mode){if(!['typed','choice'].includes(mode))return false;state.meta.settings.answerMode=mode;const r=state.run;if(r?.phase==='battle'&&!r.feedback&&r.question){const v=deck.find(x=>x.id===r.question.id);if(v)r.question=makeQuestion(v,r.question.type);}persist();return true;}
  function setAutoKana(enabled){state.meta.settings.autoKana=Boolean(enabled);persist();return state.meta.settings.autoKana;}
  function start({starter=false,source=null}={}){if(state.run&&state.run.phase!=='ended')return false;if(deck.length<3)throw Error('Mindestens drei gelernte Wörter für einen Run nötig.');const m=state.meta,maxHp=80+(m.perks.heart||0)*12+(m.training.heart||0)*10;m.runs++;state.run={id:`kd-${Date.now()}-${Math.floor(Math.random()*1e8)}`,phase:'battle',floor:1,mode:'normal',timed:false,startedAt:new Date().toISOString(),hp:maxHp,maxHp,shield:(m.equipment.ward||0)*6,atk:10+(m.perks.strike||0)*2+Math.round(2*Math.sqrt(Math.max(0,m.training.strike||0)))+(m.equipment.blade||0)*3,gold:0,goldEarned:0,xpEarned:0,kills:0,streak:0,correct:0,attempts:0,gear:[],recent:[],enemy:{name:'Paper Wisp',hp:38,maxHp:38,atk:7},question:null,feedback:null,bossDeadline:null,result:null,source:starter||source==='starter'?'starter':source==='guru'?'guru':'known'};state.run.question=makeQuestion();persist();return true;}
  const foes=[{name:'Paper Wisp',hp:38,atk:7},{name:'Ink Imp',hp:54,atk:9},{name:'Mist Fox',hp:65,atk:10}];
  function nextFloor(){const r=state.run;if(!r||r.phase!=='victory')return false;r.feedback=null;if(r.floor===3){r.phase='bossSelect';r.question=null;}else{r.floor++;const f=foes[r.floor-1];r.floorCorrect=0;r.floorAttempts=0;r.enemy={...f,maxHp:f.hp};r.phase='battle';r.question=makeQuestion();}persist();return true;}
  function boss(timed){const r=state.run;if(!r||r.phase!=='bossSelect')return false;r.phase='battle';r.floor=4;r.mode='boss';r.timed=Boolean(timed);r.floorCorrect=0;r.floorAttempts=0;const hp=Math.max(50,100-r.kills*10);r.enemy={name:'The Archivist',hp,maxHp:hp,atk:12};r.bossDeadline=r.timed?Date.now()+(60+(state.meta.equipment.hourglass||0)*5+(r.gear.includes('hourglass')?10:0))*1000:null;r.question=makeQuestion();persist();return true;}
  function expired(){const r=state.run;return Boolean(r?.phase==='battle'&&r.timed&&r.bossDeadline&&Date.now()>=r.bossDeadline);}
  function finish(won,reason){const r=state.run;if(!r||r.phase==='ended')return;const m=state.meta;if(won)m.wins++;m.bestFloor=Math.max(m.bestFloor,r.floor);m.history.unshift({id:r.id,at:new Date().toISOString(),won,reason,correct:r.correct,attempts:r.attempts,kills:r.kills,shards:0,gold:r.goldEarned||0,xp:r.xpEarned||0});m.history=m.history.slice(0,30);r.result={won,reason,shards:0,gold:r.goldEarned||0,xp:r.xpEarned||0};r.phase='ended';r.question=null;r.feedback=null;persist();}
  function timeout(){if(expired()){finish(false,'Die Boss-Zeit ist abgelaufen.');return true;}return false;}
  function isCorrect(q,value){const chosen=String(value??'').trim();if(!chosen)return false;if(q.type==='jpMeaning')return(q.alt||[q.correct]).some(x=>norm(x)===norm(chosen));if(q.type==='reading')return(q.alt||[q.correct]).some(x=>kana(x)===kana(chosen)||toHiragana(x)===toHiragana(chosen));if(['deJapanese','cloze'].includes(q.type))return(q.alt||[q.correct]).some(x=>norm(x)===norm(chosen)||toHiragana(x)===toHiragana(chosen));return(q.alt||[q.correct]).some(x=>norm(x)===norm(chosen));}
  function answer(input){const r=state.run;if(!r||r.phase!=='battle'||!r.question||r.feedback)return null;if(expired()){timeout();return null;}const q=r.question,chosen=String(input??'').trim();if(!chosen)return null;const correct=isCorrect(q,chosen);r.attempts++;r.floorAttempts=(r.floorAttempts||0)+1;r.recent.push(q.id);r.recent=r.recent.slice(-Math.min(5,Math.max(1,deck.length-1)));state.weak[q.id]=clamp((state.weak[q.id]||0)+(correct?-.35:1),0,6);let damage=0,hurt=0,earnedGold=0,earnedXp=0,levelUps=0;const m=state.meta;
    if(correct){r.correct++;r.floorCorrect=(r.floorCorrect||0)+1;r.streak++;const special=m.equipment.focus||0;damage=r.atk+(r.gear.includes('focus')&&r.streak%3===0?10:0)+(special&&r.streak%3===0?3+special*3:0);if(r.mode==='boss')damage=Math.min(damage,Math.ceil(r.enemy.maxHp/(r.timed?4:3)));r.enemy.hp=Math.max(0,r.enemy.hp-damage);earnedGold=r.source==='starter'?1:2;earnedXp=r.source==='starter'?1:3;if(r.enemy.hp<=0){r.kills++;window.KotobaDungeonBridge?.publish?.({id:`${r.id}:floor${r.floor}`,runId:r.id,floor:r.floor,kind:r.floor===4?'boss':'enemy',mode:r.timed?'timed':'normal',source:r.source,hits:r.floorCorrect,attempts:r.floorAttempts});earnedGold+=(r.mode==='boss'?22:12);earnedXp+=(r.mode==='boss'?25:12);}m.gold+=earnedGold;r.gold+=earnedGold;r.goldEarned+=earnedGold;r.xpEarned+=earnedXp;levelUps=addXP(earnedXp);
    }else{r.streak=0;hurt=Math.max(0,r.enemy.atk-r.shield);r.shield=Math.max(0,r.shield-r.enemy.atk);r.hp=Math.max(0,r.hp-hurt);}
    r.feedback={correct,chosen,damage,hurt,hint:q.hint,earnedGold,earnedXp,levelUps,expiresAt:Date.now()};if(r.hp<=0)finish(false,'Die Gruppe braucht eine Pause.');else if(r.enemy.hp<=0){if(r.floor===4)finish(true,'Boss besiegt!');else{r.phase='victory';r.loot=null;}}persist();return{correct,damage,hurt,earnedGold,earnedXp,levelUps,enemyDefeated:r.enemy.hp<=0,runFinished:r.phase==='ended'};
  }
  function advance(){const r=state.run;if(!r)return false;if(r.phase==='victory')return nextFloor();if(r.phase!=='battle'||!r.feedback)return false;if(expired()){timeout();return false;}r.feedback=null;r.question=makeQuestion();persist();return true;}
  function abandon(){if(!state.run||state.run.phase==='ended')return false;finish(false,'Run freiwillig beendet.');return true;}
  function resetRun(){if(state.run&&state.run.phase!=='ended')return false;state.run=null;persist();return true;}
  // V0.2 compatibility: previously bought shard perks stay active. No new shard rewards.
  function perk(key){const m=state.meta,lvl=m.perks[key]||0;if(state.run&&state.run.phase!=='ended'||!['heart','strike'].includes(key)||lvl>=4)return false;const price=10+lvl*10;if(m.shards<price)return false;m.shards-=price;m.perks[key]=lvl+1;persist();return true;}
  function snapshot(){return clone(state);}
  window.KotobaDungeonEngine={version:4,setDeck,setMode,setAutoKana,start,answer,advance,boss,timeout,expired,abandon,resetRun,perk,buy,train,exchangeShards,shopPrice,levelNeed,snapshot,getQuestion:makeQuestion,equipment:EQUIPMENT,toHiragana,_test:{norm,toHiragana,kana,read,isCorrect,makeQuestion,addXP}};
})();
